replicaCount: 1

image:
  repository: localhost:5001/order-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "kubernetes"
  - name: POSTGRES_HOST
    value: "postgresql.infra.svc.cluster.local"
  - name: POSTGRES_PORT
    value: "5432"
  - name: POSTGRES_DB
    value: "order_db"
  - name: POSTGRES_USER
    value: "saga"
  - name: POSTGRES_PASSWORD
    value: "saga-password"
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: "redpanda.infra.svc.cluster.local:9092"
  - name: JAEGER_ENDPOINT
    value: "http://jaeger-collector.observability.svc.cluster.local:14268/api/traces"

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 5
